# ~/.tmux.conf

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'rose-pine/tmux'
set -g @rose_pine_variant 'main' # Options are 'main', 'moon' or 'dawn' 
set -g @rose_pine_user 'on' # Turn on the username component in the statusbar

# set -ogq @catppuccin_window_text " #W"
# set -ogq @catppuccin_window_current_text " #W"

# Options to make tmux more pleasant
# set -g mouse on
# set -g default-terminal "tmux-256color"
set-window-option -g xterm-keys on
set -s set-clipboard on
set -g allow-passthrough on

# set -g automatic-rename off
# set -g allow-rename off


# Configure the catppuccin plugin
# run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
# set -g @catppuccin_flavor "mocha"
# set -g @catppuccin_window_status_style "rounded" # "default", "rounded", "slanted", "none"

# set -g focus-events on
# set -g status-style bg=default

#Set lengths 
set -g status-right-length 100
set -g status-left-length 100
set -g status-justify centre


# set -g @catppuccin_window_default_text "#W"
# set -g @catppuccin_window_current_text "#W"
# set -g @catppuccin_window_text "#W"
# set -ogq @catppuccin_window_text " #W"
# set -ogq @catppuccin_window_current_text " #W"



# set -gF status-left "#{@catppuccin_status_session}"
# # set -gF window-status-current-format "#[bg=#{@ctp_mauve},fg=#{@ctp_crust}] ##I ##T "
## move away from catppuccin## set -g status-left '#[fg=#{E:@catppuccin_color_text},bg=#{E:@catppuccin_color_blue},bold] #{W} #[fg=#{E:@catppuccin_color_blue},bg=default,nobold]'
# set -g status-left '#[fg=#{@rose_pine_base},bg=#{@rose_pine_foam},bold] #{W} #[fg=#{@rose_pine_foam},bg=default,nobold]'
# set -g status-right "#{E:@catppuccin_status_application}"
# set -agF status-right "#{E:@catppuccin_status_cpu}"
# set -ag status-right "#{E:@catppuccin_status_session}"
# set -ag status-right "#{E:@catppuccin_status_uptime}"
# set -agF status-right "#{E:@catppuccin_status_battery}"

run '~/.tmux/plugins/tpm/tpm'
